FROM ubuntu:22.04
ENV DEBIAN_FRONTEND noninteractive
# Install dependencies
RUN apt-get update && \
    apt-get install -y curl git 

# Install Node.js
FROM node:18.04

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port on which your Node.js application will run
EXPOSE 3000

# Command to run your Node.js application
CMD ["npm", "start"]
