FROM ubuntu:22.04
ENV DEBIAN_FRONTEND noninteractive
# Install dependencies
RUN apt-get update && \
    apt-get install -y curl git && \
    rm -rf /var/lib/apt/lists/*

# Install NVM
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

# Use NVM in the shell
SHELL ["/bin/bash", "-c"]

# Install Node.js 18 and set it as default
RUN source ~/.nvm/nvm.sh && \
    nvm install 18 && \
    nvm alias default 18

# Verify installation
RUN node -v && npm -v

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port on which your Node.js application will run
EXPOSE 3000

# Command to run your Node.js application
CMD ["npm", "start"]
